language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed amrsekilly/udagram-api-feed:v5
  - docker tag udagram-api-user amrsekilly/udagram-api-user:v5
  - docker tag udagram-frontend amrsekilly/udagram-frontend:v7
  - docker tag reverseproxy amrsekilly/reverseproxy:v5

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push amrsekilly/udagram-api-feed:v5
  - docker push amrsekilly/udagram-api-user:v5
  - docker push amrsekilly/udagram-frontend:v7
  - docker push amrsekilly/reverseproxy:v5
